[profile.default]
solc_version = '0.8.22'
# evm_version = 'paris'
src = 'scripts'
out = 'out'
test = 'test/foundry'
cache_path = 'cache'
libs = [
    # We provide a set of useful contract utilities
    # in the lib directory of @layerzerolabs/toolbox-foundry:
    # 
    # - forge-std
    # - ds-test
    # - solidity-bytes-utils
    'node_modules/@layerzerolabs/toolbox-foundry/lib',
    'node_modules',
]
fs_permissions = [{ access = "read-write", path = "./"}]

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to ou own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    'frax-std/=node_modules/frax-standard-solidity/src/',
    '@tempo/=node_modules/tempo/docs/specs/src/',
    "tempo-std/=node_modules/tempoxyz/tempo-std/src/"
]

via_ir = false
optimizer = true
optimizer_runs = 200
